# frozen_string_literal: true

require_relative "manifests"
require_relative "adapter"
require_relative "family/stm32f4"

module BareRubyProt
  # The whole of one firmware, written into the target's own build directory: the board
  # adapter, the HAL configuration, the linker script and the Makefile that compiles
  # startup, CMSIS, the pinned HAL sources and the generated units with the pinned GCC.
  # Nothing is copied into an external project, because there is none — the repository
  # owns reset, clocks and main now, and CubeMX is not part of the answer.
  class Stm32CubeBuild
    # The program owns main. The board adapter brings HAL and the clock up, the program
    # runs, and a board has nowhere to return to, so it idles.
    ENTRY = <<~CPP
      extern "C" void bareruby_board_start(void);
      int main(void) {
          bareruby_board_start();
          bareruby_startup();
          bareruby_main();
          for (;;) {
          }
      }
    CPP

    def initialize(target, sources:, units: [], debug: false, exceptions: true)
      @target = target
      @sources = sources
      @debug = debug
      @exceptions = exceptions
      @board = Stm32CubeBinding::Manifests.board(target.machine.key)
      @device = @board.device
      @family = Stm32CubeBinding::FAMILIES.fetch(@board.family)
      @clock = @family.clock(@board)
    end

    def files
      {
        "manifest.txt" => manifest,
        "Makefile" => makefile,
        "bareruby_program.ld" => @family.linker_script(@device),
        @family::HAL_CONF_FILE => @family.hal_conf(@board)
      }.merge(Stm32CubeBinding::Adapter.new(@board).files)
    end

    # puts goes where a desk can watch. Whether there is such a place is the board's
    # answer: a board without a stdout UART drops the calls at the first stage.
    def stdout? = !@board.stdout_uart.nil?

    def entry = ENTRY

    def mcu_options
      options = "-mcpu=#{@device.core} -mthumb"
      return options if @device.fpu == "none"

      "#{options} -mfpu=#{@device.fpu} -mfloat-abi=#{@device.float_abi}"
    end

    # -fno-use-cxa-atexit keeps a static destructor from registering with a runtime that
    # never runs one, on a board with nowhere to exit to.
    def cxx_options
      "-std=gnu++14 -fno-rtti -fno-use-cxa-atexit#{@exceptions ? '' : ' -fno-exceptions'}"
    end

    # What was built, from what, and from which layer each description came — the
    # record flashing and every later question reads instead of working it out again.
    def manifest
      stdout = @board.stdout_uart
      <<~MANIFEST
        target = #{@target.name}
        board = #{@target.machine.key}
        triple = #{@target.isa.triple}
        chip = #{@target.machine.chip}
        family = #{@board.family}
        device = #{@device.key}
        board_source = #{Stm32CubeBinding::Manifests.provenance(@board)}
        device_source = #{Stm32CubeBinding::Manifests.provenance(@device)}
        toolchain = arm-none-eabi-g++
        language_standard = gnu++14
        mcu_options = #{mcu_options}
        compile_options = #{cxx_options}
        clock = #{@clock.summary}
        generated_sources = #{@sources.join(' ')}
        stdout_channel = #{stdout ? stdout.instance : 'none'}
        debug = #{@debug ? 'enabled' : 'disabled'}
        exceptions = #{@exceptions ? 'enabled' : 'disabled'}
        openocd_interface = #{@board.openocd['interface']}
        openocd_target = #{@board.openocd['target']}
        artifact = bareruby_program.elf
        build_command = make -j
      MANIFEST
    end

    # Everything is found by basename through VPATH: the HAL and startup inside the
    # pinned checkout the second stage names as CUBE, the shared binding units one
    # directory up, the generated board files beside the Makefile. Debug against
    # release is decided here, at generation, so the Makefile holds one truth.
    def makefile
      <<~MAKE
        # Generated by the first stage. The second stage provides TOOLCHAIN and CUBE.
        TOOLCHAIN ?= arm-none-eabi
        CUBE ?= $(error CUBE is not set: the second stage names the pinned STM32Cube checkout)
        CC   = $(TOOLCHAIN)-gcc
        CXX  = $(TOOLCHAIN)-g++
        SIZE = $(TOOLCHAIN)-size

        BUILD = out
        ARTIFACT = bareruby_program.elf

        MCU = #{mcu_options}
        OPTIMIZATION = #{@debug ? '-Og -g3' : '-O2'}

        DEFINES  = -DUSE_HAL_DRIVER -D#{@device.define}
        INCLUDES = -I. -I.. \\
        #{include_lines}

        COMMON   = $(MCU) $(DEFINES) $(INCLUDES) $(OPTIMIZATION) -Wall \\
                   -ffunction-sections -fdata-sections
        CFLAGS   = $(COMMON) -std=gnu11
        CXXFLAGS = $(COMMON) #{cxx_options}
        ASFLAGS  = $(MCU) $(OPTIMIZATION) -x assembler-with-cpp

        LDFLAGS  = $(MCU) -Tbareruby_program.ld -specs=nano.specs -specs=nosys.specs \\
                   -Wl,--gc-sections -Wl,-Map=$(BUILD)/bareruby_program.map \\
                   -static -Wl,--start-group -lc -lm -Wl,--end-group

        VPATH = .. \\
                $(CUBE)/#{@family::HAL_SOURCE_DIRECTORY} \\
                $(CUBE)/#{File.dirname(@family::SYSTEM_SOURCE)} \\
                $(CUBE)/#{@family::STARTUP_DIRECTORY}

        C_SOURCES   = bareruby_board.c #{File.basename(@family::SYSTEM_SOURCE)} \\
        #{hal_lines}
        CXX_SOURCES = #{cxx_names.join(" \\\n              ")}
        AS_SOURCES  = #{@device.startup}

        OBJECTS = $(addprefix $(BUILD)/,$(C_SOURCES:.c=.o) $(CXX_SOURCES:.cpp=.o) $(AS_SOURCES:.s=.o))

        all: $(ARTIFACT)

        $(BUILD)/%.o: %.c
        \t@mkdir -p $(dir $@)
        \t$(CC) -c $(CFLAGS) $< -o $@

        $(BUILD)/%.o: %.cpp
        \t@mkdir -p $(dir $@)
        \t$(CXX) -c $(CXXFLAGS) $< -o $@

        $(BUILD)/%.o: %.s
        \t@mkdir -p $(dir $@)
        \t$(CC) -c $(ASFLAGS) $< -o $@

        # Linked by the C++ driver, which is what brings in the runtime the generated
        # units are compiled against.
        $(ARTIFACT): $(OBJECTS) bareruby_program.ld
        \t$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
        \t$(SIZE) $@

        .PHONY: all
      MAKE
    end

    def include_lines
      @family::INCLUDE_DIRECTORIES.map { |directory| "           -I$(CUBE)/#{directory}" }
                                  .join(" \\\n")
    end

    def hal_lines
      @family::HAL_SOURCES.map { |source| "              #{source}" }.join(" \\\n")
    end

    # The units pass 12 chose, by basename: VPATH already knows the shared ones sit one
    # directory up, and keeping the selection preserves the feature-based link boundary.
    def cxx_names = @sources.map { |source| File.basename(source) }
  end
end
